import { test } from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { build } from 'esbuild';
const sqlite = new DatabaseSync(':memory:');
sqlite.exec('PRAGMA foreign_keys=ON');
sqlite.exec(readFileSync('drizzle/0000_romantic_hydra.sql','utf8'));
const DB={prepare(sql){let args=[];const query={bind(...values){args=values;return query},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){return sqlite.prepare(sql).run(...args)}};return query},async batch(statements){sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}};
globalThis.piloopTestEnv={DB};
const compiled=await build({entryPoints:['app/api/toys/route.ts'],bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'test-env',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env = globalThis.piloopTestEnv;',loader:'js'}))}}]});
const {GET,POST}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
const call=(payload,origin='https://piloop.test')=>POST(new Request('https://piloop.test/api/toys',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(payload)}));
test('Independent saved hearts, protected confirmation, replay safety and memory persistence',async()=>{
 let data=await (await GET()).json();assert.equal(data.toys.length,5);assert.ok(data.toys.every(t=>t.awakened_at===null));
 const id=data.toys[0].id;
 assert.equal((await call({id,action:'awaken',key:'wrong',confirmed:true})).status,400);
 assert.equal((await call({id,action:'awaken',key:'PILOOP-DEMO',confirmed:false})).status,400);
 assert.equal((await call({id,action:'awaken',key:'PILOOP-DEMO',confirmed:true},'https://untrusted.test')).status,403);
 assert.equal((await call({id,action:'reset'})).status,400);
 assert.equal((await call({id:'unknown',action:'awaken'})).status,400);
 data=await (await call({id,action:'awaken',key:'PILOOP-DEMO',confirmed:true})).json();
 const first=data.toys[0];assert.ok(first.genesis_id);assert.ok(first.awakened_at);
 data=await (await call({id,action:'awaken',key:'PILOOP-DEMO',confirmed:true})).json();
 assert.equal(data.toys[0].genesis_id,first.genesis_id);assert.equal(data.toys[0].awakened_at,first.awakened_at);assert.equal(data.toys[1].awakened_at,null);
 const requestId=crypto.randomUUID();await call({id,action:'memory',text:'Our first day',requestId});await call({id,action:'memory',text:'Our first day',requestId});
 await call({id,action:'name',name:'Marek’s fox'});
 data=await(await GET()).json();assert.equal(data.memories.length,1);assert.equal(data.memories[0].toy_id,id);assert.equal(data.toys[0].name,'Marek’s fox');assert.equal(data.toys[0].genesis_id,first.genesis_id);
 assert.equal((await call({id,action:'memory',text:'x'.repeat(2001),requestId:crypto.randomUUID()})).status,400);
});
