'use client';
import {Volume2,Vibrate,Play,Square} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import type {HeartbeatController} from '@/hooks/use-heartbeat';
const labels={cs:{title:'Vnímej jeho srdce',sound:'Zvuk srdce',vibration:'Jemné vibrace',volume:'Hlasitost',start:'Přehrát tlukot',stop:'Zastavit přehrávání',starting:'Zrušit spouštění',unsupported:'Tento prohlížeč vibrace nepodporuje. Safari na iPhonu umožňuje zvuk, nikoliv řízené vibrace.',supported:'Krátké dvojité pulzy. Odezvu a sílu vibrací určuje telefon.',audioError:'Zvuk se nepodařilo spustit. Zkus znovu klepnout na Přehrát tlukot a zkontroluj hlasitost telefonu.',vibrationError:'Telefon vibrace nepovolil. Můžeš dál používat zvuk.',choose:'Zapni zvuk s nenulovou hlasitostí nebo vibrace.',note:'Přehrávání se vypne při odchodu z této obrazovky nebo skrytí aplikace.',playing:'Přehrává se tlukot. Vypnutí zvuku a vibrací nemění život srdce.',idle:'Připraveno k poslechu'},en:{title:'Feel its heartbeat',sound:'Heartbeat sound',vibration:'Gentle vibration',volume:'Volume',start:'Play heartbeat',stop:'Stop playback',starting:'Cancel starting',unsupported:'This browser does not support vibration. Safari on iPhone supports sound, but not controlled vibration.',supported:'Short double pulses. The response and vibration strength depend on your phone.',audioError:'Sound could not start. Tap Play heartbeat again and check your phone volume.',vibrationError:'Your phone did not allow vibration. You can still use sound.',choose:'Enable sound above zero volume, or vibration.',note:'Playback stops when you leave this screen or hide the app.',playing:'Heartbeat is playing. Stopping sound and vibration does not stop its life.',idle:'Ready when you are'}};
export function HeartbeatControls({heartbeat:h,lang}:{heartbeat:HeartbeatController;lang:'cs'|'en'}){
 const t=labels[lang];const active=h.status!=='idle';const available=(h.sound&&h.volume>0)||(h.vibration&&h.supported);
 return <section className="heartbeat-controls" aria-labelledby="heartbeat-title"><h3 id="heartbeat-title">{t.title}</h3><div className="heartbeat-option"><label htmlFor="heart-sound"><Volume2 size={17}/>{t.sound}</label><Switch id="heart-sound" checked={h.sound} onCheckedChange={h.setSound} disabled={!h.ready}/></div><div className="heartbeat-volume"><div><label id="heart-volume-label">{t.volume}</label><output>{h.volume}%</output></div><Slider ref={element=>{element?.querySelector('[role="slider"]')?.setAttribute('aria-label',t.volume)}} aria-label={t.volume} aria-labelledby="heart-volume-label" min={0} max={100} step={5} value={[h.volume]} onValueChange={v=>h.setVolume(v[0])} disabled={!h.sound||!h.ready}/></div><div className="heartbeat-option"><label htmlFor="heart-vibration"><Vibrate size={17}/>{t.vibration}</label><Switch id="heart-vibration" checked={h.vibration} onCheckedChange={h.setVibration} disabled={!h.supported||!h.ready} aria-describedby="vibration-help"/></div><p id="vibration-help" className="heartbeat-help">{h.supported?t.supported:t.unsupported}</p><button className={active?'secondary':'primary'} onClick={()=>{if(active)h.stop();else void h.start()}} disabled={!h.ready||(!active&&!available)}>{active?<Square size={16}/>:<Play size={16}/>} {h.status==='starting'?t.starting:active?t.stop:t.start}</button><p className="heartbeat-status" role="status">{!available?t.choose:h.status==='playing'?t.playing:t.note}</p>{h.error&&<p className="heartbeat-error" role="alert">{h.error==='audio'?t.audioError:t.vibrationError}</p>}</section>
}
