'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Heart,BookOpen,Sparkles,ArrowLeft,LockKeyhole,RefreshCw,Feather,Check,Volume2,VolumeX} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {type Toy,type Memory} from '@/lib/catalog';
import {useHeartbeat} from '@/hooks/use-heartbeat';
import {HeartbeatControls} from './heartbeat-controls';
import {HeartLifePreview} from './heart-life-preview';
const copy={
 cs:{collection:'Moje PILOOP',heart:'Srdce',memories:'Vzpomínky',passport:'Pas',title:'Každé srdce má svůj příběh.',intro:'Pět postaviček. Pět životů, které mohou začít.',demo:'Ukázková sbírka',notice:'Ukázkové kusy bez ověření NFC. Probuzení a vzpomínky se ukládají.',sleep:'Neprobuzené',living:'Žije',open:'Otevřít',back:'Zpět do sbírky',ready:'První tep je na tobě.',alive:'Jeho příběh právě běží.',sleepdesc:'Srdce zatím čeká. Můžeš ho ponechat neprobuzené, nebo rozhodnout o jeho prvním tepu.',livedesc:'Datum prvního tepu zůstává navždy součástí tohoto příběhu.',awaken:'Probudit srdce',age:'Věk srdce',first:'První tep',notyet:'Zatím neprobuzeno',art:'Digitální podoba podle návrhu. Skutečný výrobek zatím není nafocený.',key:'Aktivační klíč',demoKey:'Pro vyzkoušení použij PILOOP-DEMO.',verify:'Pokračovat',confirm:'Chceš opravdu probudit toto srdce?',warning:'Probuzení je trvalé. V konečném produktu tím začne jediný život, který stárne a jednou skončí. Nelze ho vrátit, zastavit ani restartovat.',agree:'Rozumím a chci probudit srdce tohoto ukázkového kusu.',cancel:'Ponechat neprobuzené',saving:'Ukládám…',success:'První tep. Začíná váš příběh.',saved:'Uloženo',error:'Spojení se nepodařilo. Zkus to znovu. Poslední uložená data zůstávají zachována.',keyError:'Zadej ukázkový klíč PILOOP-DEMO.',retry:'Zkusit znovu',loading:'Načítám tvoji sbírku…',note:'Zachyť společný okamžik',placeholder:'Co si chceš zapamatovat?',save:'Uložit vzpomínku',empty:'První společná vzpomínka může začít právě tady.',name:'Jméno postavičky',saveName:'Uložit jméno',identity:'Identita postavičky',serial:'Ukázkové číslo',edition:'Edice',auth:'Ověření fyzické hračky',authValue:'Není připojeno',genesis:'Záznam probuzení',physicalAge:'Datum výroby',unknown:'Dosud neuvedeno',model:'Životní model',modelValue:'Ukázkový režim bez automatického konce života',legacy:'Legacy',legacyInfo:'V konečném produktu zůstane po ukončení života postavička i celý její příběh dostupný. Tato verze neurčuje skutečné datum konce. Samostatná ukázka konce života nemění uložený život postavičky.',privacy:'Soukromá první verze',sound:'Zvuk srdce',pause:'Pozastavit animaci',resume:'Spustit animaci',refresh:'Obnovit stav',verified:'Načteno',seconds:'sekund',days:'dní',hours:'hodin',minutes:'minut',new:'Nové srdce',savedHint:'Uloženo online. Po návratu můžeš pokračovat.',demoConfirm:'Tato akce mění pouze ukázkový kus. Žádná fyzická hračka nebude aktivována.'},
 en:{collection:'My PILOOP',heart:'Heart',memories:'Memories',passport:'Passport',title:'Every heart has a story.',intro:'Five characters. Five lives waiting to begin.',demo:'Demo collection',notice:'Demo pieces without NFC verification. Awakenings and memories are saved.',sleep:'Unawakened',living:'Living',open:'Open',back:'Back to collection',ready:'The first beat is yours to choose.',alive:'A story already unfolding.',sleepdesc:'Its heart is waiting. You can keep it unawakened, or choose the moment of its very first beat.',livedesc:'The moment of its first heartbeat will always belong to this story.',awaken:'Awaken the heart',age:'Heart age',first:'First heartbeat',notyet:'Not yet awakened',art:'Digital appearance based on the design. The physical piece has not yet been photographed.',key:'Awakening key',demoKey:'Use PILOOP-DEMO to try the ceremony.',verify:'Continue',confirm:'Do you really want to awaken this heart?',warning:'Awakening is permanent. In the finished product it starts a single life that ages and eventually ends. It cannot be reversed, paused or restarted.',agree:'I understand and want to awaken the heart of this demo piece.',cancel:'Keep unawakened',saving:'Saving…',success:'The first heartbeat. Your story begins.',saved:'Saved',error:'Unable to connect. Please try again. Previously saved data remains unchanged.',keyError:'Enter the demo key PILOOP-DEMO.',retry:'Try again',loading:'Opening your collection…',note:'Keep a moment together',placeholder:'What would you like to remember?',save:'Save memory',empty:'Your first shared memory can begin right here.',name:'Character name',saveName:'Save name',identity:'Character identity',serial:'Demo number',edition:'Edition',auth:'Physical toy verification',authValue:'Not connected',genesis:'Awakening record',physicalAge:'Manufactured',unknown:'Not yet recorded',model:'Life model',modelValue:'Demo mode without automatic end of life',legacy:'Legacy',legacyInfo:'In the finished product, the character and its story remain available after its life ends. This version does not determine an actual end date. The separate end of life preview does not change the character’s saved life.',privacy:'Private first version',sound:'Heartbeat sound',pause:'Pause animation',resume:'Play animation',refresh:'Refresh state',verified:'Loaded',seconds:'seconds',days:'days',hours:'hours',minutes:'minutes',new:'A new heart',savedHint:'Saved online. Your story will be here when you return.',demoConfirm:'This action changes only the demo piece. No physical toy will be activated.'}
};
function Portrait({toy,large=false,animate=false,pulse=0}:{toy:Toy;large?:boolean;animate?:boolean;pulse?:number}){return <div className={'portrait '+(large?'large':'')} role="img" aria-label={toy.en+' · '+toy.tier} style={{backgroundPosition:`${toy.x}% center`}}>{animate&&<span key={pulse} className="heart-glow" style={{left:toy.heartX+'%',top:toy.heartY+'%'}}><span aria-hidden="true"/></span>}</div>}
export default function Piloop(){
 const lang='en' as 'cs'|'en';const t=copy[lang];
 const [toys,setToys]=useState<Toy[]>([]),[memories,setMemories]=useState<Memory[]>([]),[selected,setSelected]=useState<string|null>('DEMO-BASIC-001'),[tab,setTab]=useState('heart');
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[last,setLast]=useState('');
 const [dialog,setDialog]=useState(false),[step,setStep]=useState(1),[key,setKey]=useState(''),[agree,setAgree]=useState(false),[animate,setAnimate]=useState(true);
 const [draft,setDraft]=useState(''),[name,setName]=useState(''),[now,setNow]=useState(Date.now()),[offset,setOffset]=useState(0);
 const pendingMemory=useRef<string|null>(null),inFlight=useRef(false);
 const apply=useCallback((data:{toys:Toy[];memories:Memory[];serverTime:string})=>{setToys(data.toys);setMemories(data.memories);setLast(data.serverTime);setOffset(Date.parse(data.serverTime)-Date.now());setNow(Date.parse(data.serverTime));},[]);
 const load=useCallback(async()=>{try{setError('');const r=await fetch('/api/toys',{cache:'no-store'});if(!r.ok)throw Error();apply(await r.json());}catch{setError('error')}finally{setLoading(false)}},[apply]);
 useEffect(()=>{load();const motion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(motion)setAnimate(false);},[load]);
 useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem('piloop-language',lang)},[lang]);
 useEffect(()=>{const i=setInterval(()=>setNow(Date.now()+offset),1000);return()=>clearInterval(i)},[offset]);
 useEffect(()=>{const onFocus=()=>{if(!inFlight.current)load()};window.addEventListener('focus',onFocus);return()=>window.removeEventListener('focus',onFocus)},[load]);
 const toy=toys.find(x=>x.id===selected);const living=!!toy?.awakened_at;
 const heartbeat=useHeartbeat(`${selected}:${tab}`);const {sound,setSound}=heartbeat;
 useEffect(()=>{if(toy)setName(toy.name)},[toy?.id]);
 const title=(x:Toy)=>x.name||(lang==='cs'?x.cs:x.en);
 const date=(s:string)=>new Date(s).toLocaleString(lang==='cs'?'cs-CZ':'en-GB',{dateStyle:'medium',timeStyle:'short'});
 const age=()=>{if(!toy?.awakened_at)return t.notyet;const sec=Math.max(0,Math.floor((now-Date.parse(toy.awakened_at))/1000));if(sec<60)return `${sec} ${t.seconds}`;if(sec<3600)return `${Math.floor(sec/60)} ${t.minutes}`;if(sec<86400)return `${Math.floor(sec/3600)} ${t.hours}`;return `${Math.floor(sec/86400)} ${t.days}`};
 async function mutate(body:object){if(inFlight.current)return false;inFlight.current=true;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/toys',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected,...body})});const data=await r.json() as {toys:Toy[];memories:Memory[];serverTime:string;error?:string};if(!r.ok){setError(data.error==='key'?'keyError':'error');return false;}apply(data);return true;}catch{setError('error');return false}finally{inFlight.current=false;setBusy(false)}}
 async function awaken(){const token=await heartbeat.prepare();const ok=await mutate({action:'awaken',key,confirmed:agree});if(ok){setDialog(false);setMessage(t.success);if(token!==undefined)void heartbeat.start(token)}}

 function choose(x:Toy){setSelected(x.id);setTab('heart');setDraft('');setName(x.name);setMessage('');setError('');pendingMemory.current=null;window.scrollTo({top:0,behavior:'smooth'})}
 return <div className="app-shell">
  <header className="app-header"><button className="header-collection text-button" onClick={()=>{if(!busy)setSelected(null)}}><Heart size={17}/>{t.collection}</button><button className="logo-button" onClick={()=>{if(!busy)setSelected(null)}} aria-label="PILOOP"><img src="/assets/logo.png" alt="PILOOP More Than a Toy"/></button><span aria-hidden="true"/></header>
  <main>
  {error&&<div className="error" role="alert">{t[error as 'error'|'keyError']} {!dialog&&<button onClick={load} disabled={busy}><RefreshCw size={15}/>{t.retry}</button>}</div>}
  {message&&<div className="success" role="status"><Check size={17}/>{message}</div>}
  {loading?<div className="loading"><Heart size={32}/><p>{t.loading}</p></div>:!toy?<>
   <div className="collection-heading"><div><span className="eyebrow">{t.collection}</span><h1>{t.title}</h1><p>{t.intro}</p></div><span className="count">{String(toys.length).padStart(2,'0')} <Heart size={23}/></span></div>
   <div className="collection-grid">{toys.map((x,i)=><button key={x.id} className="toy-card" onClick={()=>choose(x)}><div className="card-top"><span>{x.tier}</span><span className="index">0{i+1}</span></div><Portrait toy={x}/><div className="card-bottom"><div><h2>{title(x)}</h2><span className="serial">{x.id}</span></div><span className={'state '+(x.awakened_at?'is-living':'')}><Heart size={14} fill={x.awakened_at?'currentColor':'none'}/>{x.awakened_at?t.living:t.sleep}</span></div></button>)}</div>
   <p className="art-caption">{t.art}</p><div className="collection-footer"><Heart size={18}/><span>More Than a Toy</span><span className="signature">design by Marek S.</span></div>
  </>:<>
   <div className="detail-top"><button className="text-button" onClick={()=>setSelected(null)} disabled={busy}><ArrowLeft size={17}/>{t.back}</button><span className="serial">{toy.id}</span></div>
   <div className="detail-grid"><nav className="collection-rail" aria-label={t.collection}><span className="eyebrow">{t.collection}</span>{toys.map(x=><button key={x.id} aria-pressed={x.id===selected} onClick={()=>choose(x)} disabled={busy}><Portrait toy={x}/><span className="rail-label"><strong>{title(x)}</strong><small>{x.tier}</small></span>{x.awakened_at&&<Heart className="rail-heart" size={12} fill="currentColor"/>}</button>)}</nav><section className="character-stage"><div className="stage-heading"><span className="edition-mark" data-edition={toy.tier}>{toy.tier}</span><h1>{title(toy)}</h1><span className={'state '+(living?'is-living':'')}><Heart size={14}/>{living?t.living:t.sleep}</span></div><Portrait toy={toy} large animate={living&&animate} pulse={heartbeat.status==='playing'?heartbeat.pulse:0}/><p className="signature">design by Marek S.</p><span className="stage-serial">{toy.id}</span><div className="stage-action">{!living?<button className="primary" onClick={()=>{setStep(1);setKey('');setAgree(false);setError('');setDialog(true)}}><Heart size={19}/>{t.awaken}</button>:<button className="secondary" onClick={()=>setAnimate(!animate)}>{animate?t.pause:t.resume}</button>}</div></section>
   <section className="character-details"><Tabs value={tab} onValueChange={setTab}><TabsList className="detail-tabs" variant="line"><TabsTrigger value="heart"><Heart/>{t.heart}</TabsTrigger><TabsTrigger value="memories"><Feather/>{t.memories}</TabsTrigger><TabsTrigger value="passport"><BookOpen/>{t.passport}</TabsTrigger></TabsList>
    <TabsContent value="heart"><div className="heart-panel"><div key={heartbeat.status==='playing'?heartbeat.pulse:0} className={'heart-symbol '+(living&&animate?'beating':'')}><span className="yarn-heart" role="img" aria-label={t.heart}/></div><span className="eyebrow">{living?'LIVING':'UNAWAKENED'}</span><h2>{living?t.alive:t.ready}</h2><p>{living?t.livedesc:t.sleepdesc}</p><div className="heart-facts"><div><span>{t.age}</span><strong>{age()}</strong></div><div><span>{t.first}</span><strong>{toy.awakened_at?date(toy.awakened_at):t.notyet}</strong></div></div>

    <HeartLifePreview key={toy.id} lang={lang} onOpen={heartbeat.stop}/>
    {living&&<HeartbeatControls heartbeat={heartbeat} lang={lang}/>}
    <button className="text-button refresh" onClick={load} disabled={busy}><RefreshCw size={14}/>{t.refresh}</button>{last&&<small>{t.verified}: {date(last)}</small>}
    <details className="legacy"><summary>{t.legacy}</summary><p>{t.legacyInfo}</p></details></div></TabsContent>
    <TabsContent value="memories"><div className="panel"><span className="eyebrow">{title(toy)}</span><h2>{t.note}</h2><form onSubmit={async e=>{e.preventDefault();pendingMemory.current=pendingMemory.current||crypto.randomUUID();if(await mutate({action:'memory',text:draft,requestId:pendingMemory.current})){setDraft('');pendingMemory.current=null;setMessage(t.saved)}}}><label className="sr-only" htmlFor="memory">{t.placeholder}</label><textarea id="memory" value={draft} onChange={e=>{setDraft(e.target.value);pendingMemory.current=null}} placeholder={t.placeholder} maxLength={2000} rows={4} required disabled={busy}/><button className="primary" disabled={busy||!draft.trim()}>{busy?t.saving:t.save}</button></form><div className="timeline">{memories.filter(m=>m.toy_id===toy.id).map(m=><article key={m.id}><time>{date(m.created_at)}</time><p>{m.text}</p></article>)}{!memories.some(m=>m.toy_id===toy.id)&&<p className="empty-note">{t.empty}</p>}{toy.awakened_at&&<article className="genesis-memory"><Heart size={17}/><time>{date(toy.awakened_at)}</time><p>{t.first}</p></article>}</div></div></TabsContent>
    <TabsContent value="passport"><div className="panel"><span className="eyebrow">PILOOP PASSPORT</span><h2>{t.identity}</h2><form className="name-form" onSubmit={async e=>{e.preventDefault();if(await mutate({action:'name',name}))setMessage(t.saved)}}><label htmlFor="toy-name">{t.name}</label><input id="toy-name" value={name} placeholder={lang==='cs'?toy.cs:toy.en} onChange={e=>setName(e.target.value)} maxLength={40} disabled={busy}/><button className="secondary" disabled={busy}>{busy?t.saving:t.saveName}</button></form><dl className="passport-list"><dt>{t.serial}</dt><dd>{toy.id}</dd><dt>{t.edition}</dt><dd>{toy.tier}</dd><dt>{t.physicalAge}</dt><dd>{t.unknown}</dd><dt>{t.auth}</dt><dd><LockKeyhole size={15}/>{t.authValue}</dd><dt>{t.genesis}</dt><dd>{toy.genesis_id||t.notyet}</dd><dt>{t.model}</dt><dd>{t.modelValue}</dd></dl><p className="art-caption">{t.art}</p><p className="signature">design by Marek S.</p></div></TabsContent>
   </Tabs></section></div>
  </>}
  </main><footer className="app-footer"><span><Sparkles size={14}/>{t.demo}</span><span>{t.notice}</span></footer>
  <Dialog open={dialog} onOpenChange={v=>{if(!busy){setDialog(v);setError('')}}}><DialogContent className="awakening-dialog" showCloseButton={!busy}><div className="ceremony-portrait">{toy&&<Portrait toy={toy}/>}</div><DialogTitle>{step===1?t.awaken:t.confirm}</DialogTitle><DialogDescription>{step===1?t.demoConfirm:t.warning}</DialogDescription>{error&&<p className="dialog-error" role="alert">{t[error as 'error'|'keyError']}</p>}{step===1?<form onSubmit={e=>{e.preventDefault();if(key==='PILOOP-DEMO'){setStep(2);setError('')}else setError('keyError')}}><label htmlFor="key">{t.key}</label><input id="key" value={key} onChange={e=>setKey(e.target.value.toUpperCase())} autoComplete="off" spellCheck={false} required/><p className="key-hint">{t.demoKey}</p><button className="primary">{t.verify}</button></form>:<><label className="check-label"><Checkbox checked={agree} onCheckedChange={v=>setAgree(v===true)} disabled={busy}/><span>{t.agree}</span></label><label className="check-label"><Checkbox checked={sound} onCheckedChange={v=>setSound(v===true)} disabled={busy}/>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>}<span>{t.sound}</span></label><label className="check-label"><Checkbox checked={heartbeat.vibration} onCheckedChange={v=>heartbeat.setVibration(v===true)} disabled={busy||!heartbeat.supported}/><span>{lang==='cs'?'Jemné vibrace telefonu':'Gentle phone vibration'}</span></label>{!heartbeat.supported&&<p className="heartbeat-help">{lang==='cs'?'Tento prohlížeč vibrace nepodporuje.':'This browser does not support vibration.'}</p>}<button className="primary" onClick={awaken} disabled={!agree||busy}>{busy?t.saving:t.awaken}</button></>}<button className="text-button" onClick={()=>{setDialog(false);setError('')}} disabled={busy}>{t.cancel}</button></DialogContent></Dialog>
 </div>
}
